[package]
name = "scrum-discord-bot"
version = "0.1.0"
edition = "2021"
authors = ["Said Rodrigues <coderflemis@gmail.com>"]

[lib]
path = "src/lib.rs"


[[bin]]
name = "http"
doc = false
path = "src/bin/http.rs"

[dependencies]
anyhow = "1.0.89"
thiserror = "1.0.64"
