global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090

  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3200"]

  - job_name: "api"
    static_configs:
      - targets: ["api:8080"]

  - job_name: "otel"
    static_configs:
      - targets: ["otel-collector:8888"]

  - job_name: "nodeexporter"
    static_configs:
      - targets: ["nodeexporter:9100"]
