application:
  port: 42069
  host: 0.0.0.0
  prefix: ""
  name: "discord-bot-rustson"
  version: v0.1.0

database:
  hosts:
    - "localhost"
  port: 27017
  username: "root"
  password: "example"
  database: "discord-bot-rustson"
  ssl: false

otel:
  endpoint: http://localhost:4317
  enable: false

prometheus:
  port: 42070
  path: /metrics

env: "local"
